name: LaTeX Compilation

on:
  push:
    branches:
      - master  # or your main branch name
  pull_request:
    branches:
      - master  # or your main branch name

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

      - name: Initialize user texmf tree (if needed)
        run: tlmgr init-usertree || echo "tlmgr already initialized"

      - name: Print the content of mydoc.tex
        run: cat mydoc.tex

      - name: Compile LaTeX document
        run: |
          pdflatex mydoc.tex
          cat mydoc.log # Add this line to print the log file

      - name: Upload PDF to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: mydoc.pdf

      - name: Debug - Print GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.LATEX_GITHUB_TOKEN }}"

      - name: Commit PDF
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mydoc.pdf
          git commit -m "Compiled LaTeX document to PDF" -a || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF} --force
        env:
          GITHUB_TOKEN: ${{ secrets.LATEX_GITHUB_TOKEN }}

