name: LaTeX Compilation

on:
  push:
    branches:
      - master # or your main branch name
  pull_request:
    branches:
      - master # or your main branch name

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        uses: dante-ev/latex-action@latest
        with:
          packages: texlive-latex-recommended, texlive-fonts-recommended, amsmath

      - name: Print the content of the dodgy tex file
        run: cat /usr/local/texlive/2024/texmf-dist/tex/latex/tools/.tex

      - name: Compile LaTeX document
        run: |
          pdflatex mydoc.tex
          # If you have bibtex
          # bibtex mydoc.aux
          # pdflatex mydoc.tex
          # pdflatex mydoc.tex

      - name: Upload PDF to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: mydoc.pdf

      - name: Commit PDF
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mydoc.pdf
          git commit -m "Compiled LaTeX document to PDF" -a || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF}
